### ISSUE TITLE
Password required to make changes to user profile

### ISSUE THREAD

**Issue by robertatinreachtechdotnet** [turboladen/hub_hub#47]
We probably don't need to require the password to make changes to a user's account.  If we do,  however,  please make sure that the change password field stay's empty (though this may be an artifact of having the browser remember the password.   In that case,  maybe the app could ignore the change password fields if there is something in the confirm password field?

Actually,  I think the best way to do this would be to have the change password section on it's own page.

**Comment by turboladen** [comment]
The password confirmation thing is a default setting of the authentication plugin I used.  It's there to prevent someone from changing your password if you, for example, accidentally forget to log out while using a public computer.  I do agree, though, that the user experience as it is is probably not the best.  I would, however, like to keep it for security's sake.  At least for now.

I'm not quite sure what you're describing here though:

> make sure that the change password field stay's empty

Stays empty when?  It's empty when I arrive at the page and empty after I make changes.  Can you provide some steps to describe what you mean?

> maybe the app could ignore the change password fields if there is something in the confirm password field?

The change password fields are ignored unless you enter something in to them.  If you enter something in to them, then the assumption is that you're intending to change your password--just like if you enter any info in any other field.  Again, I'm thinking I must be misunderstanding; could you provide steps to recreate what you mean?

In the mean time, I'll look in to moving the change password section to its own page.

**Comment by robertatinreachtechdotnet** [comment]
On 11/15/2012 01:32 PM, Steve Loveless wrote:
[snip]

> I'm not quite sure what you're describing here though:
> 
> ```
> make sure that the change password field stay's empty
> ```
> 
> Stays empty when? It's empty when I arrive at the page and empty after I
> make changes. Can you provide some steps to describe what you mean?
> [snip]
> —
> Reply to this email directly or view it on GitHub
> https://github.com/turboladen/hub_hub/issues/47#issuecomment-10426401.
> 
> I think the problem is that Firefox was auto filling in my password in 
> one of the change password fields.

I'm not sure if other people will hit that or not.

## 

In Reach Technology:    http://www.inreachtech.net/

Robert G. Werner
robert@inreachtech.net

Tel: 559.304.5122

Immigration is the sincerest form of flattery.
        -- Jack Paar

**Comment by turboladen** [comment]
Ah ok, that makes sense.  I'll look to see what the ways around this might be.

**Comment by turboladen** [comment]
@robertatinreachtechdotnet do you have, by chance, any opinion on me having removed the requirement for users to provide their password when changing their profile info?  They still, of course, have to provide a password confirmation when changing their password...

**Comment by robertatinreachtechdotnet** [comment]
On 03/11/2013 10:37 PM, Steve Loveless wrote:

> @robertatinreachtechdotnet
> https://github.com/robertatinreachtechdotnet do you have, by chance,
> any opinion on me having removed the requirement for users to provide
> their password when changing their profile info? They still, of
> course, have to provide a password confirmation when changing their
> password...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/turboladen/hub_hub/issues/47#issuecomment-14759413.
> 
> I think that is fine.  This is just a little forum.  Not their credit
> card or anything.  You could make it optional (a config option for
> security sensitive deployments) if you were really ambitious but I
> don't think it's necessary.

## 

In Reach Technology:    http://www.inreachtech.net/

Robert G. Werner
robert@inreachtech.net

Tel: 559.304.5122

The early bird who catches the worm works for someone who comes in late
and owns the worm farm.
        -- Travis McGee

**Comment by turboladen** [comment]
Ok, sounds good.  I think I'd like to leave it as is (simple) for now and see how that works for people.  Thanks for the feedback.
