### ISSUE TITLE
Possibly incorrect MIME encoding of digest ...

### ISSUE THREAD

**Issue by robertatinreachtechdotnet** [turboladen/hub_hub#73]
I'm seeing all the RAW MIME encoding in the digest rather than seeing the message itself.

**Comment by turboladen** [comment]
Yeah, looks like it's sending out all emails as one email to each person.  Changing to bcc one email to all subscribers.

**Comment by robertatinreachtechdotnet** [comment]
On 03/08/2013 05:04 PM, Steve Loveless wrote:

> Yeah, looks like it's sending out all emails as one email to each
> person. Changing to bcc one email to all subscribers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/turboladen/hub_hub/issues/73#issuecomment-14654842.
> 
> We may need to send out each mail individually to each person to keep
> the mail from being marked as spam.  BCC is one sign of spammers that
> many filters are looking for.

## 

In Reach Technology:    http://www.inreachtech.net/

Robert G. Werner
robert@inreachtech.net

Tel: 559.304.5122

Just don't compare it with a real language, or you'll be unhappy...  :-)
             -- Larry Wall in 1992May12.190238.5667@netlabs.com

**Comment by turboladen** [comment]
OK, I can do that.
