### ISSUE TITLE
Digest contains a MIME entity for each subscriber ...

### ISSUE THREAD

**Issue by robertatinreachtechdotnet** [turboladen/hub_hub#74]
The digest contains a MIME entity for each subscriber (it appears).  

Do we need to generate the digest email as a separate message to each recipient?

I'll attach an example:

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:53 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 512478297de4c_39b05083810221c4@chat.mindhub.org.mail

Hi Admin,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:55 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 5124782ba829_39b050838102248c@chat.mindhub.org.mail

Hi Cristobal,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:55 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 5124782b4ea04_39b05083810225a5@chat.mindhub.org.mail

Hi Kelly,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:55 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 5124782b94c59_39b05083810226ef@chat.mindhub.org.mail

Hi Agnes,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:56 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 5124782c1ef21_39b0508381022752@chat.mindhub.org.mail

Hi Nels,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:56 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 5124782c5782d_39b050838102284f@chat.mindhub.org.mail

Hi Jayde,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:56 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 5124782cb46a2_39b05083810229bc@chat.mindhub.org.mail

Hi Gilbert,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:57 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 5124782d203cc_39b0508381023091@chat.mindhub.org.mail

Hi Steve,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:57 -0800
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 5124782d4c591_39b0508381023139@chat.mindhub.org.mail

Hi Robert,
Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).

---- Posts from past 24 hours ----
## No posts from yesterday.

---- Responses from past 24 hours ----
## No responses from yesterday.

***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

----==_mimepart_51247829735e1_39b05083810220e5
Date: Tue, 19 Feb 2013 23:15:53 -0800
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Content-ID: 51247829835f1_39b050838102222@chat.mindhub.org.mail

<!DOCTYPE html>

<p>Hi Admin,</p>

<p>Here's your digest email of all of the posts from the past 24 hours (as of
February 19, 2013 23:15).
</p>

<hr>

<h3>Posts from past 24 hours</h3>

<p>No posts from yesterday.</p>

<hr>

<h3>Responses from past 24 hours</h3>

<p>No responses from yesterday.</p>

<hr>

<br>

<p>
***NOTE: If you'd like to stop receiving digest emails, login to chat.mindhub.org,
go to your user account's profile page, click 'Edit profile', then
edit the 'Digest email' option.

</p>

----==_mimepart_51247829735e1_39b05083810220e5--

**Comment by turboladen** [comment]
Yeah, this is definitely wrong and unintentional.  I was trying to be personable and address each person; seems easier to just send 1 email out to everyone though.

**Comment by turboladen** [comment]
This is still occurring.
